SELECT * FROM CLIENTE;
GO


CREATE PROCEDURE USP_INSERT_CLIENT
(
	@IDCLIENTE		int out,
	@NOMBRE    VARCHAR(150),
	@IDTIPODOC      int out,
	@NRODOC    VARCHAR(20),
	@DIRECCION VARCHAR(200),
	@CELULAR  VARCHAR(20),
	@CORREO     VARCHAR(50)
)
AS
BEGIN
	INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,IDTIPODOC,NRODOC,DIRRECCION,CELULAR,CORREO)
		VALUES(@IDCLIENTE,@NOMBRE,@IDTIPODOC,@NRODOC,@DIRECCION,@CELULAR,@CORREO);
END;
GO

-- Prueba
begin
	
	EXEC USP_INSERT_CLIENT 3,'Adrian', 1, '123456', 'Av Alcazar', '987654321', 'gmail';
	
end;
go
