
SELECT * FROM PEDIDO;
GO

SELECT * FROM CLIENTE

DROP PROCEDURE USP_INSERT_PEDIDO;
go

SET IDENTITY_INSERT PEDIDO ON
go

CREATE PROCEDURE USP_INSERT_PEDIDO
(
	@IDPEDIDO		int,
	@FECHA          datetime,
	@IDEMPLEADO     int,
	@IDCLIENTE      int out,
	@IDTIPOVENTA    int,
	@IDESTADO       int,
	@IDTIPOCOMP     int,
	@NROCOMP        varchar(20),
	@IMPORTE        numeric(10,2),
	@IMPUESTO       numeric(10,2),
	@TOTAL          numeric(10,2)
)

AS
BEGIN
	INSERT INTO PEDIDO(IDPEDIDO,FECHA,IDEMPLEADO,IDCLIENTE,IDTIPOVENTA,IDESTADO,IDTIPOCOMP,NROCOMP,IMPORTE,IMPUESTO,TOTAL)
		VALUES(@IDPEDIDO,@FECHA,@IDEMPLEADO,@IDCLIENTE,@IDTIPOVENTA,@IDESTADO,@IDTIPOCOMP,@NROCOMP,@IMPORTE,@IMPUESTO,@TOTAL);
END;
GO

SET IDENTITY_INSERT PEDIDO OFF
go

-- Prueba
begin
	
	EXEC USP_INSERT_PEDIDO 12,2001-02-02, '1', '3', '2', '3', '2', NULL, 60.00, 10.00, 70.00;
	
end;
go