USE [SIGPE]
GO
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'01  ', N'Departamento De Medicina Interna')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0100', N'Departamento De Medicina')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0101', N'Servicio De Medicina Interna I, Ii, Iv')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0102', N'Servicio De Medicina Interna Iii')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'02  ', N'Direccion General')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0200', N'Direccion General')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'07  ', N'Departamento De Pediatria')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0700', N'Departamento De Pediatria')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0701', N'Servicio De Pediatria')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0702', N'Servicio De Neonatología')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'08  ', N'Departamento De Gineco Obstetricia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0800', N'Departamento De Gineco Obstetricia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0801', N'Servicio De Ginecología')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0802', N'Servicio De Obstetricia Médico Quirúrgico')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0803', N'Servicio De Obstetricia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0804', N'Servicio De Reproducción Humana')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'09  ', N'Departamento De Emergencia Y Cuidados Criticos')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0900', N'Departamento De Emergencia Y Cuidados Criticos')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0901', N'Servicio De Emergencia/Trauma Shock')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0902', N'Servicio De Cuidados Intensivos')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0903', N'Servicio De Cuidados Intensivos Y Cuidados Intermedios Neonatales')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'0904', N'Servicio De Cuidados Intensivos Pediátricos')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'10  ', N'Departamento De Odontoestomatologia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1000', N'Departamento De Odontoestomatologia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1001', N'Servicio De Odontoestomatología Clínica')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1002', N'Servicio De Cirugía Bucal Y Maxilo Facial')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'11  ', N'Departamento De Anestesiología Y Centro Quirúrgico')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1100', N'Departamento Anestesiología Y Centro Quirúrgico')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1101', N'Servicio De Anestesiologia Y Cq/Terapia Del Dolor /Servicio De Cirugía Ambulatoria')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1102', N'Servicio De Anestesiología Y Centro Quirúrgico/Recuperación Post Anestésica Y Reanimación')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'12  ', N'Departamento De Patologia Clinica Y Anatomia Patologica')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1200', N'Departamento De Patologia Clinica Y Anatomia Patologica')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1201', N'Servicio De Bioquímica Y Hematología')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1202', N'Servicio De Hemoterapia Y Banco De Sangre')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1203', N'Servicio De Microbiología, Inmunología Y Biología Molecular')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1204', N'Servicio De Anatomía Patológica')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'13  ', N'Departamento De Diagnostico Por Imagenes')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1300', N'Departamento De Diagnostico Por Imágenes')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1301', N'Servicio De Radiología Convencional')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1302', N'Servicio De Ultrasonografía')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1303', N'Servicio De Radiología Intervencionista')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'14  ', N'Departamento De Medicina De Rehabilitacion')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1400', N'Departamento De Medicina De Rehabilitacion')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1401', N'Servicio De Lesiones Neuromotoras/Desarrollo Psicomotor/Terapias Especializadas')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'15  ', N'Departamento De Salud Mental')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1500', N'Departamento De Salud Mental')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1501', N'Servicio De Psicología')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1502', N'Servicio De Psiquiatría')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'16  ', N'Departamento De Nutricion Y Dietetica')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1600', N'Departamento De Nutricion Y Dietetica')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1601', N'Servicio De Alimentación/Dietoterapia/Nutrición Integral')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'17  ', N'Departamento De Servicio Social')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1700', N'Departamento De Servicio Social')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'18  ', N'Departamento De Farmacia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1800', N'Departamento De Farmacia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1801', N'Servicio De Farmacia/Farmacotecnia')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'19  ', N'Departamento De Enfermeria')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1900', N'Departamento De Enfermeria')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1901', N'Servicio De Enfermería De Consulta Externa')
INSERT [dbo].[SERVICIO] ([IDSERVICIO], [NOMBRE]) VALUES (N'1902', N'Servicio De Enfermería De Central De Esterilización')
GO
